# Generated by Django 5.0 on 2024-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_voyage_tracking_info_from_contry_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage_tracking_info',
            name='doc_status',
            field=models.BooleanField(default=True, verbose_name='documentary status'),
        ),
    ]
